services:
  # oh-my-link:
  #   build:
  #     context: .
  #     dockerfile: Dockerfile
  #   container_name: oh-my-link
  #   restart: always
  #   ports:
  #     - "8742:80"  # Port peu commun (8742) mappé au port 80 du conteneur
  #   volumes:
  #     - ./docker/nginx.conf:/etc/nginx/conf.d/default.conf
  #   networks:
  #     - oh-my-link-network

  oh-my-link-dev:
    image: node:20-alpine
    container_name: oh-my-link-dev
    restart: always
    volumes:
      - .:/app
    working_dir: /app
    command: sh -c "npm install -g pnpm && pnpm install && pnpm exec vite --host 0.0.0.0"
    ports:
      - "8742:5173"  # Port 5173 est le port par défaut de Vite
    networks:
      - oh-my-link-network

networks:
  oh-my-link-network:
    driver: bridge
